spring:
  application:
    name: users_microservice
  #cloud.config.url: http://localhost:8888
  config.import: "optional:configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        serviceId: config_service
  profiles:
    active:
      - dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
