server.port: 8888
#spring.cloud.config.server.git.uri: file://${user.home}/config-repo
spring:
  application:
    name: config-service
  profiles:
    active:
      - native

  cloud:
    config:
      server:
        native:
          search-locations=resources/config:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
