spring:
  application:
    name: notification-microservice
  #cloud.config.url: http://localhost:8888
  config.import: "optional:configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        serviceId: config-service
  profiles:
    active:
      - dev
eureka:
  client:
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
openapi:
  service:
    title: Notification service
    version: 0.0.1
    url: http://localhost:8080/notification-microservice
