spring:
  application:
    name: api_gateway_service
  config:
    import: "optional:configserver:"
  profiles:
    active:
      - dev
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        serviceId: config-service
    gateway:
      routes:
        - id: funnel-microservice
          predicates:
            - Path=/funnel-microservice/**
          uri: lb://funnel-microservice
          filters:
            - RewritePath=/funnel-microservice/(?<segment>.*),/$\{segment}
        - id: users-microservice
          predicates:
            - Path=/users-microservice/**
          uri: lb://users-microservice
          filters:
            - RewritePath=/users-microservice/(?<segment>.*),/$\{segment}
        - id: product-catalog-microservice
          predicates:
            - Path=/product-catalog-microservice/**
          uri: lb://product-catalog-microservice
          filters:
            - RewritePath=/product-catalog-microservice/(?<segment>.*),/$\{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        display-name: API Gateway Service
      - url: /users-microservice/v3/api-docs
        name: User Service
        display-name: User Service
      - url: /funnel-microservice/v3/api-docs
        name: Funnel Service
        display-name: Funnel Service
