spring:
  application:
    name: api_gateway_service
  config:
    import: "optional:configserver:"
  profiles:
    active:
      - dev
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        serviceId: config_service
    gateway:
      routes:
        - id: funnel_microservice
          predicates:
            - Path=/funnel/
          uri: localhost:8081
        - id: users_microservice
          predicates:
            - Path=/user/
          uri: localhost:8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
