spring:
  application:
    name: api_gateway_service
  config:
    import: configserver:http://localhost:8888/
  profiles:
    active:
      - dev
  cloud:
    gateway:
      routes:
        - id: funnel_microservice
          predicates:
            - Path=/funnel/
          uri: localhost:8081
        - id: users_microservice
          predicates:
            - Path=/user/
          uri: localhost:8082
