spring:
  application:
    name: api_gateway_service
  config:
    import: "optional:configserver:"
  profiles:
    active:
      - dev
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        serviceId: config-service
    gateway:
      routes:
        - id: funnel-microservice
          predicates:
            - Path=/funnel/
          uri: lb://funnel-microservice
        - id: users-microservice
          predicates:
            - Path=/api/user/**
          uri: lb://users-microservice
          filters:
            - RewritePath=/api/user(?<segment>.*),/user$\{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
