spring:
  application:
    name: funnel-microservice
  config.import: "optional:configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        serviceId: config-service
  profiles:
    active:
      - dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
openapi:
  service:
    title: Funnel service
    version: 0.0.1
    url: http://localhost:8080/funnel-microservice
