spring:
  application:
    name: funnel_microservice
  config.import: configserver:http://localhost:8888/
  profiles:
    active:
      - dev
eureka:
  client:
    serviceUrl:
    defaultZone: http://localhost:8761/eureka/
